version: "3.8"

services:
  kawa-orders-db:
    image: mysql:latest
    environment:
      MYSQL_USER: orders
      MYSQL_PASSWORD: kawaorders
      MYSQL_DATABASE: kawaordersdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3253:3307"
    expose:
      - "3307" 
    volumes:
      - orders-data:/var/lib/mysql  
    networks:
      - kawa-orders-network

  kawa-orders-app:
    container_name: kawa_orders
    build:
      context: .
    ports:
      - "8081:81"
    depends_on:
      - kawa-orders-db
    environment:
      - DATABASE_URL=mysql://orders:kawaorders@kawa-orders-db:3307/kawaordersdb
    networks:
      - kawa-orders-network

volumes:
  orders-data:

networks:
  kawa-orders-network: