version: "3.8"

services:
  kawa-orders-db:
    image: mysql:latest
    environment:
      MYSQL_USER: orders
      MYSQL_PASSWORD: kawaorders
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    expose:
      - "3306" 
    volumes:
      - orders-data:/var/lib/mysql  
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - kawa-orders-network
      - kawa-shared-network

  kawa-orders-app:
    container_name: kawa_orders
    build:
      context: .
    ports:
      - "8081:81"
    depends_on:
      - kawa-orders-db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://orders:kawaorders@kawa-orders-db:3306/order_db
    networks:
      - kawa-orders-network
      - kawa-shared-network

volumes:
  orders-data:

networks:
  kawa-orders-network:
  kawa-shared-network:
    external: true