name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  CI_CD_Pipeline:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git User
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Vérifie l'installation de Docker Compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start Docker containers
        run: |
          docker-compose up -d
          sleep 60  

      - name: Check Docker container logs
        run: |
          docker-compose logs kawa-orders-app

      - name: Verify Docker containers are running
        run: |
          docker ps

           # Vérifie si le conteneur kawa-orders-app est en cours d'exécution
          if ! docker ps | grep kawa-orders-app; then
            echo "Le conteneur kawa-orders-app n'est pas en cours d'exécution !"
            exit 1
          fi

          # Vérifie si le port 8081 est accessible sur le conteneur kawa-orders-app
          if ! nc -zv localhost 8081; then
            echo "Le port 8081 sur le conteneur kawa-orders-app n'est pas accessible !"
            exit 1
          fi

          # Effectue une requête HTTP pour vérifier si l'API répond
          # if ! curl -s http://localhost:8081/ | grep "expected_response"; then
          #   echo "L'API sur http://localhost:8081/ ne répond pas comme prévu !"
          #   exit 1
          # fi

      - name: Checkout release branch with token
        if: success()  # Si les images sont construites et les conteneurs démarrent
        uses: actions/checkout@v3
        with:
          ref: release
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Merge main into release
        if: success()  # Si les conteneurs sont en cours d'exécution
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Merging main into release"
          git fetch origin main
          git checkout -B release origin/main
          git push --force https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} release
          echo "Merge et push forcé de la branche main vers release validé"

      - name: Check test failure
        if: failure()  # Si une étape précédente a échoué
        run: echo "Échec du test ou du démarrage des conteneurs !"
