name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -u root -proot -e 'SHOW DATABASES;' > /dev/null 2>&1; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Copy database
        run: |
          python tests/copy_db.py

      - name: Run tests
        run: |
          python -m unittest discover -s tests
