# .github/workflows/ci.yml
name: test-1

on:
  push:
    branches:
      - main  # Branche à surveiller pour les commits
  pull_request:
    branches:
      - main  # Branche pour les pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE test_db;"
        sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'rootpassword';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"

    - name: Prepare database
      run: |
        mysql -uroot -prootpassword test_db -e "
        CREATE TABLE IF NOT EXISTS orders (
            id_order INT AUTO_INCREMENT PRIMARY KEY,
            customerId INT NOT NULL,
            createdAt DATETIME NOT NULL,
            updated_at DATETIME,
            status INT NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS order_products (
            id_order_products INT AUTO_INCREMENT PRIMARY KEY,
            productId INT NOT NULL,
            quantity INT NOT NULL,
            id_order INT NOT NULL,
            FOREIGN KEY (id_order) REFERENCES orders(id_order)
        );
        INSERT INTO orders (customerId, createdAt) VALUES (1, '2024-09-14 10:00:00');
        INSERT INTO order_products (productId, quantity, id_order) VALUES (1, 10, 1);
        "

    - name: Run tests
      run: |
        python -m unittest discover -s tests
